### ISSUE TITLE
Giao diện còn thiếu vài chức năng

### ISSUE THREAD

**Issue by Phu3502** [cdchu2/sek2n2#1]
Hiện tại giao diện vẫn còn đang thiếu tính năng như trending repository giúp truy cập nhanh các xu thế hiện tại. Nên có thêm chức năng ghim để nhanh chóng truy cập vào các repository cần thiết.

**Comment by cdchu2** [comment]
Cảm ơn vì đã đánh giá repo, tôi sẽ cố gắng fix và update những chức năng còn lại sớm nhất có thể ;)

**Comment by cdchu2** [comment]
- [ ] Đã fix
