### ISSUE TITLE
#Fix UI and update full features

### ISSUE THREAD

**Issue by cdchu2** [cdchu2/sek2n2#2]
- [x] **Giao diện người dùng chưa hoàn chỉnh** 

- [x] **Một số tính năng bị thiếu cần được update**

### Ô nào nhận fix -> comment!!!

**Comment by Phuo250302** [comment]
Xin task UI bạn nhé!!

**Comment by cdchu2** [comment]
@Phuo250302 Uki b ui ;))

**Comment by Phu3502** [comment]
Vậy còn task kia tôi làm nốt nhé

**Comment by Phu3502** [comment]
> @Phuo250302 Uki b ui ;))

Cái task còn lại chưa ai làm thì để tôi nhé

**Comment by cdchu2** [comment]
> > @Phuo250302 Uki b ui ;))
> 
> Cái task còn lại chưa ai làm thì để tôi nhé

Okee baby <3
